#!/usr/bin/env bash
# This script transfers a file from the client to a server using scp

if [ "$#" -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# Assign arguments to variables for better readability
FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY="$4"

# Use scp to transfer the file
if scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE_PATH" "${USERNAME}@${SERVER_IP}:~/"; then
	echo  "File successfully transferred to ${USERNAME}@${SERVER_IP}:~/"
else
	echo "Error: File transfer failed."
	exit 1
fi
