#!/usr/bin/env bash
# The configuration of web-01 to have an HTTP response header

# Update packages and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create an index file
echo "Hello world!" | sudo tee /var/www/html/index.html

# Redirect traffic to a custom page
update_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Thandeka325 permanent;"

sudo sed -i "s/server_name _;/$update_string/" /etc/nginx/sites-enabled/default

# Create a custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Add the custom HTTP response header
#Ensures the header is added withing the approriate server block
sudo sed -i "server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Test Nginx configuration for syntax errors
sudo nginx -t

# Restart the Nginx service
sudo service nginx restart
