#!/usr/bin/env bash
# Script that configures Nginx server with a custom header

# Exit on error
set -e

# Update and install Nginx
apt-get -y update
apt-get -y install nginx

# Define hostname dynamically
HOSTNAME=$(hostname)

# Create a custom index page and 404 page
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

# Add custom 404 page and location block
sed -i "s/server_name _;/server_name _;\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default

# Add custom header in the server block
sed -i "/server_name _;/a \\tadd_header X-Served-By \"$HOSTNAME\";" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
