#!/usr/bin/env bash
# Debugging Nginx, to ensure its running and listening on port 80 of all the server’s active IPv4 IPs.
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
sudo kill "$(pgrep 'nginx' | head -1)"
