#!/usr/bin/env bash
# This script displays a list of currently running processes, in a user-orientated format with process hierarchy.

ps -e -o user,pid,pcpu,pmem,vsz,rss,tty,stat,start,time,cmd --forest


