#!/usr/bin/env bash
# This script displays the username, user ID, and home directory path for each user in the /etc/passwd/ file.

while IFS=: read -r username _ user_id _ _ home_directory _; do
	echo "$username:$user_id:$home_directory"
done < /etc/passwd
