#!/usr/bin/env bash
# This script displays information about users from the /etc/passwd file.

while IFS=: read -r username password user_id gid info home_directory shell; do
	echo "The user $username is part of the $gid gang,"\
	"lives in $home_directory and rides $shell."\
	"$gid's place is protected by the passcode $password,"\
    	"more info about the user here: $info"
done < /etc/passwd
