#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code and displays this data.

awk '{print $1, $9}' apache-access.log | \
	awk '{count[$1, $2]++} END {for (key in count) print count[key], key}' | \
	sort -rn
