#!/usr/bin/env bash
# This script configures the container so that Nginx runs as nginx user 
# and listens on all active IPs on port 8080

chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/^(\s*#?\s*user\s+).*/\1nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/listen\s+80\s*;/listen 8080;/' /etc/nginx/sites-available/default
sed -Ei 's/listen\s+\[::\]:80\s*;/listen [::]:8080;/' /etc/nginx/sites-available/default
service nginx restart
