#!/usr/bin/env bash
# This script configures the container to fit the following requirements:
# nginx must be running as nginx user
# nginx must be listening on all active IPs on port 8080

# Give neccesarry permissions to Nginx configuration file
chmod 644 /etc/nginx/nginx.conf

# Update Nginx configuration to use user 'nginx' and listen on port 8080
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-available/default
pkill apache2
# Restart Nginx to apply changes
service nginx restart
